name: Auto Merge 'prod' to 'master'
on:
  push:
    branches: [ prod ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch origin master
          git fetch origin prod
          git checkout master
          git merge prod --ff-only
          git push origin master
